"""empty message

Revision ID: d5f3ed9bda88
Revises: 9e57663ede7e
Create Date: 2026-03-18 16:52:58.659387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f3ed9bda88'
down_revision = '9e57663ede7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_funded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('purpose')
        batch_op.drop_column('amount_funded')

    # ### end Alembic commands ###
