"""added balance credit_score rating total_invested

Revision ID: f99984056708
Revises: 94f52a1c700f
Create Date: 2026-04-08 14:06:23.075016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99984056708'
down_revision = '94f52a1c700f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False))
        batch_op.add_column(sa.Column('total_loans', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_invested', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_invested')
        batch_op.drop_column('total_loans')
        batch_op.drop_column('rating')
        batch_op.drop_column('credit_score')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
